### ISSUE TITLE
Is the manifest+json MIME type actually required?

### ISSUE THREAD

**Issue by alexkrolick** [boyofgreen/ManUp.js#2]
Do browsers actually check the MIME type if valid JSON is served at the target of the manifest `link`? Will they start doing so if they don't now?

**Comment by boyofgreen** [comment]
So far the only implementation out in the wild is chrome, and it does absolutely check the mime type.    However, for manup.js we don't actually ckeck it.

**Comment by cmitz** [comment]
Chrome also does not check for the correct MIME type, but *is* required. You can look it up here: https://w3c.github.io/manifest/#media-type-registration

However, @boyofgreen , the file extension should be `.webmanifest` and not `.json`, as you stated in the README :-)
![image](https://cloud.githubusercontent.com/assets/5594436/20747460/835415e8-b6ea-11e6-87f2-75af7b635a10.png)
(image from the same W3 page as linked above)

**Comment by boyofgreen** [comment]
cool thanks for the info.  I'll update the readme.
